import type { Metadata } from "next";
import Link from "next/link";
import LabExperience from "@/components/lab/LabExperience";

export const metadata: Metadata = {
    title: "The Lab — Vandan Sheth",
    description:
        "An interactive experiment: watch breadth-first and depth-first search reason through a graph, step by step. Built on a deterministic engine, rendered as an editorial page.",
};

export default function LabPage() {
    return (
        <>
            {/* Slim, self-contained top bar — no dependency on the portfolio nav. */}
            <header className="border-b border-rule bg-paper">
                <div className="container-page flex items-center justify-between py-4">
                    <Link
                        href="/"
                        className="font-display text-lg font-semibold tracking-tight text-ink hover:text-accent transition-colors"
                    >
                        Vandan Sheth
                    </Link>
                    <Link
                        href="/"
                        className="eyebrow transition-colors hover:text-accent"
                    >
                        ← Back to portfolio
                    </Link>
                </div>
            </header>

            <main className="py-16 md:py-24">
                <div className="container-page">
                    {/* Editorial masthead (server-rendered text). */}
                    <p className="eyebrow mb-4">Vandan&apos;s Intelligence · An experiment</p>
                    <h1 className="font-display text-4xl md:text-6xl font-medium tracking-tight mb-5">
                        Watch an algorithm{" "}
                        <em className="italic text-accent font-normal">think</em>
                    </h1>
                    <p className="max-w-2xl text-lg text-ink-soft mb-12">
                        Pick a problem and step through it. Not bouncing bars — the reasoning
                        laid out like a page: a live graph, a monospace state ledger, and the
                        frontier expanding one ring at a time. The traversal is generated by the
                        real algorithm, so every step is correct by construction.
                    </p>

                    <LabExperience />
                </div>
            </main>

            <footer className="border-t border-rule py-10">
                <div className="container-page flex items-center justify-between">
                    <p className="eyebrow text-ink-faint">The Lab · Vandan Sheth</p>
                    <Link href="/" className="eyebrow transition-colors hover:text-accent">
                        ← Back to portfolio
                    </Link>
                </div>
            </footer>
        </>
    );
}
